services:
  - type: web
    name: feel-the-distribution
    env: python
    buildCommand: pip install -r requirements.txt
    plan: starter
    startCommand: |
      export PYTHON_ENV=production
      export MALLOC_ARENA_MAX=2
      export PYTHONMALLOC=malloc
      export MALLOC_TRIM_THRESHOLD_=100000
      export NODE_OPTIONS="--max-old-space-size=400"
      export PORT=${PORT:-10000}
      echo "Configurando puerto: $PORT en $(hostname)"
      python optimize_media.py
      find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
      find . -name "*.pyc" -delete
      python -c "import gc; gc.collect()"
      # Verificar que puertos están abiertos
      echo "Puertos en uso antes de iniciar:"
      netstat -tulpn 2>/dev/null || echo "netstat no disponible"
      # Iniciar con uvicorn directamente
      python -m reflex init
      uvicorn create_app:asgi_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: MAX_WORKERS
        value: 1
      - key: PYTHONUNBUFFERED
        value: true
      - key: WEB_CONCURRENCY
        value: 1
      - key: PORT
        value: 10000 