services:
  - type: web
    name: feel-the-distribution
    env: static
    buildCommand: python optimize_media.py && python -m reflex init && python -m reflex export --frontend-only
    staticPublishPath: .web/_static
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400 